name: Auto Update
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Fetch current dynamic.m3u from Gist
        run: |
          curl -sL "https://gist.githubusercontent.com/rzrb0/${{ secrets.GIST_ID }}/raw/dynamic.m3u" -o dynamic.m3u
          echo "File scaricato."

      - name: Install Python dependencies
        run: pip install requests

      - name: Update dynamic.m3u (Supabase), log.txt
        env:
          SUPABASE_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: python get_lc.py

      - name: Deploy dynamic.m3u to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: dynamic.m3u
          file_type: text

      - name: Deploy log.txt to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: log.txt
          file_type: text
